use_frameworks!

platform :ios, '9.0'

target 'react-native-screens_Example' do
  pod 'react-native-screens', :path => '../'

  target 'react-native-screens_Tests' do
    inherit! :search_paths

    
  end
end
